name: cancellation_token
description: Easy cancellation for tasks using cancellation tokens in Dart.
version: 0.0.1-dev
repository: https://github.com/jonathanpetercole/dart-cancellation-token

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  lints: ^1.0.0
