name: cancellation_token
description: Easy async task cancellation for tasks using cancellation tokens in Dart.
version: 1.4.0
repository: https://github.com/jonathanpetercole/dart-cancellation-token

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies: 
  meta: ^1.8.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.5
  fake_async: ^1.3.1
