name: cancellation_token
description: Easy async task cancellation for tasks using cancellation tokens in Dart.
version: 1.3.2
repository: https://github.com/jonathanpetercole/dart-cancellation-token

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies: 
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
  fake_async: ^1.2.0
